apiVersion: v1
kind: Service
metadata:
  labels:
    app: ppx-ui
    component: ppx-ui-dev
  name: ppx-ui-dev
  namespace: teamwork
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 80
      nodePort: 30998
  selector:
    app: ppx-ui
    component: ppx-ui-dev
    tier: frontend
  sessionAffinity: None
  type: NodePort
